
services:
  web:
    image: ghcr.io/nv-9/fishysparadise.com:prod
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`fishysparadise.com`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=webresolver"
      - "com.centurylinklabs.watchtower.enable=true"
  
  panel:
    image: pufferpanel/pufferpanel:latest
    restart: unless-stopped
    environment:
      PUFFERPANEL_DB: mysql
      PUFFERPANEL_DB_HOST: panel-db
      PUFFERPANEL_DB_USER: pufferpanel
      PUFFERPANEL_DB_PASSWORD: pufferpanel
      PUFFERPANEL_DB_NAME: pufferpanel
    depends_on:
      - panel-db
    ports:
      - "25565:25565"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.panel.rule=Host(`panel.fishysparadise.com`)"
      - "traefik.http.routers.panel.entrypoints=websecure"
      - "traefik.http.routers.panel.tls.certresolver=webresolver"
      - "traefik.http.services.pufferpanel.loadbalancer.server.port=8080"
    volumes:
      - /opt/pufferpanel:/var/lib/pufferpanel

  panel-db:
    image: mysql:9.2.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pufferpanel
      MYSQL_USER: pufferpanel
      MYSQL_PASSWORD: pufferpanel
    volumes:
      - panel_db:/var/lib/mysql

  reverse-proxy:
    image: traefik:v3.1
    command:
      # - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"      
      - "--certificatesresolvers.webresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.webresolver.acme.email=nalabotuviswamedha@gmail.com"
      - "--certificatesresolvers.webresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock"

  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"


volumes:
  letsencrypt:
  panel_db: