
services:
  web:
    image: ghcr.io/nv-9/fishysparadise.com:prod
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`fishysparadise.com`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=webresolver"
      - "com.centurylinklabs.watchtower.enable=true"
 
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.webresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.webresolver.acme.email=nalabotuviswamedha@gmail.com"
      - "--certificatesresolvers.webresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock"

  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  
  panel:
    image: githubyumao/mcsmanager-web:latest
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/panel/web/data:/opt/mcsmanager/web/data"
      - "/panel/web/logs:/opt/mcsmanager/web/logs"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.panel.rule=Host(`panel.fishysparadise.com`)"
      - "traefik.http.routers.panel.entrypoints=websecure"
      - "traefik.http.routers.panel.tls.certresolver=webresolver"

  daemon:
    image: githubyumao/mcsmanager-daemon:latest
    restart: unless-stopped
    environment:
      - MCSM_DOCKER_WORKSPACE_PATH=/panel/daemon/data/InstanceData
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/panel/daemon/data:/opt/mcsmanager/daemon/data"
      - "/panel/daemon/logs:/opt/mcsmanager/daemon/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.daemon.rule=Host(`daemon.fishysparadise.com`)"
      - "traefik.http.routers.daemon.entrypoints=websecure"
      - "traefik.http.routers.daemon.tls.certresolver=webresolver"
      - "traefik.http.services.daemon.loadbalancer.server.port=24444"


volumes:
  letsencrypt:
