
services:
  web:
    image: ghcr.io/nv-9/fishysparadise.com:prod
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`fishysparadise.com`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=webresolver"
      - "com.centurylinklabs.watchtower.enable=true"

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: unless-stopped
    depends_on:
      - panel-db
    environment:
      APP_URL: "https://panel.fishysparadise.com"
      TRUSTED_PROXIES: "**"
      DB_CONNECTION: "mysql"
      DB_HOST: "panel-db"
      DB_PORT: "3306"
      DB_DATABASE: "pterodactyl"
      DB_USERNAME: "pterodactyl"
      DB_PASSWORD: "pterodactyl"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.panel.rule=Host(`panel.fishysparadise.com`)"
      - "traefik.http.routers.panel.entrypoints=websecure"
      - "traefik.http.routers.panel.tls.certresolver=webresolver"
    volumes:
      - panel_site_data:/var/www/html
    command: >
      /bin/sh -c "
      [ ! -f /var/www/html/.env ] && cp /var/www/html/.env.example /var/www/html/.env && php artisan key:generate;
      php artisan migrate --force;
      chown -R www-data:www-data /var/www/html;
      php artisan queue:restart;
      supervisord --nodaemon
      "

  wings:
    image: ghcr.io/pterodactyl/wings:latest
    restart: unless-stopped
    depends_on:
      - panel
    environment:
      WINGS_CONFIG_LOCATION: "/etc/pterodactyl/config.yml"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - wings_data:/etc/pterodactyl
    ports:
      - "8080:8080"
      - "2022:22"
      - "25565:25565"

  panel-db:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "pterodactyl"
      MYSQL_USER: "pterodactyl"
      MYSQL_PASSWORD: "pterodactyl"
    volumes:
      - panel_db:/var/lib/mysql

  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.webresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.webresolver.acme.email=nalabotuviswamedha@gmail.com"
      - "--certificatesresolvers.webresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock"

  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  letsencrypt:
  panel_db:
  panel_site_data:
  wings_data:
